### ISSUE TITLE
Rebuild package with Sandstorm 0.169

### ISSUE THREAD

**Issue by kentonv** [pgrm/swagger-editor-sandstorm#3]
Sandstorm 0.166 and 0.167 had a bug in sandstorm-http-bridge which would occasionally cause it to hang. The currently-released version of Swagger Editor had the bad luck to be built in this window. You can reproduce the problem by repeatedly doing "reload frame" -- eventually, the grain stops responding.

This can be fixed by rebuilding the app with Sandstorm 0.168 or 0.169 and re-submitting.

Sorry for the inconvenience! (This doesn't usually happen.)

**Comment by pgrm** [comment]
Hi @kentonv - finally got time to revisit this - I've updated the app today to the latest swagger-editor version. The vagrant spk hasn't changed since beginning of June, so that's the same. Can you tell me how I can check which sandstorm version I used to build the new version?

Thank you

**Comment by paulproteus** [comment]
Hi @pgrm !

The version of Sandstorm used to build the package can be found at:

http://local.sandstorm.io:6080/about

when you're doing

`$ vagrant-spk dev`

If you find the version number is lower than desired, you can do:

``` bash
$ vagrant-spk vm ssh
$ sudo sandstorm update
```

and that should update it.

**Comment by pgrm** [comment]
ok thx, it shows me version number 0.174 now, so I guess the new package has the correct version so I'll close it now
