### ISSUE TITLE
App does not launch anymore

### ISSUE THREAD

**Issue by theSoenke** [pgrm/swagger-editor-sandstorm#4]
Since the update to 2.10.3 i can't launch the app anymore. When i create a grain the site is loading forever.
I've tried it on oasis. This is the debug log:

> **\* Uncaught exception ***
> sandstorm/sandstorm-http-bridge.c++:1887: failed: execvp(argvp[0], argvp): Permission denied; argvp[0] = /opt/app/.sandstorm/launcher.sh
> stack: 0x5087e9 0x5087da 0x47442f

**Comment by paulproteus** [comment]
I am also able to reproduce this issue.

**Comment by pgrm** [comment]
Hi @theSoenke I've pushed a small fix, I can't reproduce the issue anymore, can you check it please

**Comment by paulproteus** [comment]
FWIW I can confirm that the new build fixes the issue!

**Comment by theSoenke** [comment]
The update solved the issue for me too. Thanks!
